version: '3.7'

services:
  api:
    image: bakingbad/bcdhub-api:3.4
    volumes:
      - ${PROJECT_ROOT_DIR}/bcd/sandbox.yml:/app/api/sandbox.yml
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:20000
    depends_on:
      - elastic
      - db
      - mq
    ports:
      - 42000:14000
    logging:
      options:
        max-size: 10m
        max-file: '5'

