version: '3.7'

services:
  gui:
    image: bakingbad/bcdhub-gui:3.4
    entrypoint: /bin/bash
    depends_on:
      - api
    ports:
      - 8009:80
    logging:
      options:
        max-size: 10m
        max-file: '5'
