version: '3.7'

services:
  mq:
    image: rabbitmq:latest
    volumes:
      - mqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging:
      options:
        max-size: 10m
        max-file: '5'

volumes:
  mqdata:
