version: '3.7'

services:
  bcdgui:
    restart: always
    image: bakingbad/bcdhub-gui:${TAG:-latest}
    entrypoint: /bin/bash
    command: -c "mv config.box.json config.json && nginx -g 'daemon off;'"
    depends_on:
      - api
    ports:
      - 8009:80
    logging:
      options:
        max-size: 10m
        max-file: '5'
