version: '3.7'

services:
  bcdgui:
    image: bakingbad/bcdhub-gui:3.0
    environment:
      - BCD_ENV=sandbox
    entrypoint: /bin/bash
    command: -c "mv config.box.json config.json && nginx -g 'daemon off;'"
    depends_on:
      - bcdapi
    ports:
      - 8009:80
    logging:
      options:
        max-size: 10m
        max-file: '5'
