version: '3.7'

services:
  bcdindexer:
    image: bakingbad/bcdhub-indexer:3.4
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=release
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:20000
    depends_on:
      - elastic
      - mq
    logging:
      options:
        max-size: 10m
        max-file: '5'
