version: '3.7'

services:
  bcdmetrics:
    image: bakingbad/bcdhub-metrics:2.6
    command: -f config.yml -f config.box.yml -f config.bbbox.yml
    volumes:
      - ${PROJECT_ROOT_DIR}/bbbox/config.yml:/app/metrics/config.bbbox.yml
    environment:
      - GIN_MODE=release
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - elastic
      - mq
      - db
    logging:
      options:
        max-size: 10m
        max-file: '5'
