version: '3.7'

services:

  explorer:
    image: blockwatch/tzstats
    environment:
      # this is accessed from the browser
      TZSTATS_API_URL: http://localhost:${TZ_INDEX_PORT}
    ports:
      - 3001:8000
    depends_on:
      - tzindex
